(define-key evil-normal-state-map "i" nil)
(define-key evil-normal-state-map "I" nil)
(define-key evil-normal-state-map "J" nil)
(define-key evil-normal-state-map "gi" nil)
(define-key evil-normal-state-map "gJ" nil)
(define-key evil-window-map "j" nil)
(define-key evil-window-map "J" nil)
(define-key evil-window-map "k" nil)
(define-key evil-window-map "K" nil)
(define-key evil-window-map "l" nil)
(define-key evil-window-map "L" nil)
(define-key evil-window-map "n" nil)
(define-key evil-motion-state-map "e" nil)
(define-key evil-motion-state-map "E" nil)
(define-key evil-motion-state-map "j" nil)
(define-key evil-motion-state-map "k" nil)
(define-key evil-motion-state-map "l" nil)
(define-key evil-motion-state-map "K" nil)
(define-key evil-motion-state-map "L" nil)
(define-key evil-motion-state-map "n" nil)
(define-key evil-motion-state-map "N" nil)
(define-key evil-motion-state-map "ge" nil)
(define-key evil-motion-state-map "gE" nil)
(define-key evil-motion-state-map "gj" nil)
(define-key evil-motion-state-map "gk" nil)
(define-key evil-motion-state-map "C-e" nil)
(define-key evil-motion-state-map "gn" nil)
(define-key evil-motion-state-map "gN" nil)
(define-key evil-visual-state-map "I" nil)
(define-key evil-visual-state-map "i" nil)
(define-key evil-operator-state-map "i" nil)

;; Normal state
(define-key evil-normal-state-map "l" 'evil-insert)
(define-key evil-normal-state-map "L" 'evil-insert-line)
(define-key evil-normal-state-map "N" 'evil-join)
(define-key evil-normal-state-map "gl" 'evil-insert-resume)
(define-key evil-normal-state-map "gN" 'evil-join-whitespace)

;; Window commands
(define-key evil-window-map "n" 'evil-window-down)
(define-key evil-window-map "N" 'evil-window-move-very-bottom)
(define-key evil-window-map "e" 'evil-window-up)
(define-key evil-window-map "E" 'evil-window-move-very-top)
(define-key evil-window-map "i" 'evil-window-right)
(define-key evil-window-map "I" 'evil-window-move-far-right)
(define-key evil-window-map "j" 'evil-window-new)

;; Motion state
(define-key evil-motion-state-map "k" 'evil-forward-word-end)
(define-key evil-motion-state-map "K" 'evil-forward-WORD-end)
(define-key evil-motion-state-map "n" 'evil-next-line)
(define-key evil-motion-state-map "e" 'evil-previous-line)
(define-key evil-motion-state-map "i" 'evil-forward-char)
(define-key evil-motion-state-map "E" 'evil-lookup)
(define-key evil-motion-state-map "I" 'evil-window-bottom)
(define-key evil-motion-state-map "j" 'evil-search-next)
(define-key evil-motion-state-map "J" 'evil-search-previous)
(define-key evil-motion-state-map "gk" 'evil-backward-word-end)
(define-key evil-motion-state-map "gK" 'evil-backward-WORD-end)
(define-key evil-motion-state-map "gn" 'evil-next-visual-line)
(define-key evil-motion-state-map "ge" 'evil-previous-visual-line)
(define-key evil-motion-state-map "C-k" 'evil-scroll-line-down)

;; Text objects
(define-key evil-motion-state-map "gj" 'evil-next-match)
(define-key evil-motion-state-map "gJ" 'evil-previous-match)

;; Visual state
(define-key evil-visual-state-map "L" 'evil-insert)
(define-key evil-visual-state-map "l" 'evil-inner-text-objects-map)

;; Operator-Pending statea
(define-key evil-operator-state-map "l" 'evil-inner-text-objects-map)
